set nocompatible " must be first

set runtimepath^=~/.vim/bundle/tabular
set runtimepath^=~/.vim/bundle/vim-easy-align
set runtimepath^=~/.vim/bundle/rainbow_parentheses.vim

set ai
set backspace=2
set smartindent
set tabstop=3
set shiftwidth=3
set expandtab
set mouse=a
set autochdir
set cursorline
set formatoptions-=t " disable linebreak word wrap in insert mode
set history=50
set ruler
set showcmd
set incsearch
set nowrap

set number relativenumber
augroup numbertoggle
   autocmd!
   autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
   autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

syntax enable
" colorscheme monokai
colorscheme molokai
let g:molokai_original=1
set guifont=Consolos:h16

" rainbow parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

augroup set_file_type
   autocmd!
"    autocmd BufNewFile,BufRead .bashrc*,bashrc,.bash_profile*,bash_profile* setf=bash
   autocmd BufNewFile,BufRead *.v,*.sv,*.vs,*.svh setf=verilog
   autocmd BufNewFile,BufRead *.v,*.sv,*.vs,*.svh set syntax=verilog
augroup END

augroup comment_group_of_code
   autocmd!
   autocmd FileType c,cpp,java,scala,verilog      let b:comment_leader = '// '
   autocmd FileType bash,sh,ruby,python,make,tmux let b:comment_leader = '# '
   autocmd FileType tex,matlab                    let b:comment_leader = '% '
   autocmd FileType vim                           let b:comment_leader = '" '
augroup END
noremap <silent> cc :<C-B>silent <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:nohlsearch<CR>
noremap <silent> cu :<C-B>silent <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:nohlsearch<CR>

set laststatus=2
set statusline=
set statusline+=%1*\ %y     " file type
set statusline+=%2*\ %.50F  " full file path
set statusline+=%2*\ %r\ %m " read only, modified
set statusline+=%=
set statusline+=%3*\ %p%%
set statusline+=%3*\ [%c:%l/%L]

inoremap jj <Esc>
nnoremap <space> :

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
