export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
export TERM='screen-256color'

alias la='ls -a'
alias ll='ls -l'
# alias tmux='tmux -2'

alias gcc='gcc-11' # link to homebrew gcc
alias g++='g++-11' # link to homebrew g++

# default prompt: \h:\W \u\$
export PS1="[\u:\e[1;34m\W\e[0m\$]"
